#!/usr/bin/env bash
#
# Prepends a released version's notes to CHANGELOG.md, right below the
# `<!-- releases -->` anchor, so the file stays newest-first.
#
# Usage: .github/scripts/changelog-update.sh <version> <notes-file>

set -euo pipefail

cd "$(dirname "$0")/../.."

version=${1:?usage: changelog-update.sh <version> <notes-file>}
notes=${2:?usage: changelog-update.sh <version> <notes-file>}

file='CHANGELOG.md'
anchor='<!-- releases -->'
today=$(date -u '+%Y-%m-%d')

# Recreated rather than treated as fatal: a release must not half-finish
# because the file was moved or deleted at some point.
if [[ ! -f $file ]]; then
  cat >"$file" <<MARKDOWN
# Changelog

Every release of this project is listed here, newest first. The file is
generated by the \`Release\` workflow from the [Conventional Commits](https://www.conventionalcommits.org/)
merged into \`main\`, and versions follow [Semantic Versioning](https://semver.org/).

Do not edit the entries by hand — write good commit messages instead. The
comment below marks where new releases are inserted; keep it in place.

$anchor
MARKDOWN
fi

anchor_line=$(grep -n -m 1 -F "$anchor" "$file" | cut -d: -f1)

[[ -n $anchor_line ]] || {
  echo "$file has no '$anchor' anchor to insert below" >&2
  exit 1
}

if [[ -n ${GITHUB_REPOSITORY:-} ]]; then
  server=${GITHUB_SERVER_URL:-https://github.com}
  heading="## [${version}](${server}/${GITHUB_REPOSITORY}/releases/tag/v${version}) — ${today}"
else
  heading="## ${version} — ${today}"
fi

updated=$(mktemp)
trap 'rm -f "$updated"' EXIT

{
  head -n "$anchor_line" "$file"
  printf '\n%s\n\n' "$heading"
  cat "$notes"
  tail -n "+$((anchor_line + 1))" "$file"
} >"$updated"

cp "$updated" "$file"
